version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: backend-image:latest
    ports:
      - "5001:5001"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 